import type { Metadata } from 'next';
import { Alumni_Sans, Inter } from 'next/font/google';
import Analytics from '../components/Metrics/Analytics';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const alumni = Alumni_Sans({
  subsets: ['latin'],
  variable: '--font-alumni',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ua"
      className={`${inter.variable} ${alumni.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="bg-bg-black">
        <Analytics gaId="G-JFR75PSGYP" clarityId="v8y9anztsk" />
        {children}
      </body>
    </html>
  );
}
